// PlatformImages.js

export const PlatformImages = {
    "3DO": require("../assets/game app images/3DO.png"),
    "Atari 2600": require("../assets/game app images/Atari 2600.png"),
    "Atari 5200": require("../assets/game app images/Atari 5200.png"),
    "Atari 7800": require("../assets/game app images/Atari 7800.png"),
    "Atari Jaguar": require("../assets/game app images/Atari Jaguar.png"),
    "Atari Lynx": require("../assets/game app images/Atari Lynx.png"),
    "Colecovision": require("../assets/game app images/Colecovision.png"),
    "Hyperscan": require("../assets/game app images/Hyperscan.png"),
    "Intellivision": require("../assets/game app images/Intellivision.png"),
    "Nintendo NES": require("../assets/game app images/Nintendo NES.png"),
    "Super Nintendo": require("../assets/game app images/Super Nintendo.png"),
    "Game Boy": require("../assets/game app images/Game Boy.png"),
    "Game Boy Advance": require("../assets/game app images/Game Boy Advance.png"),
    "Nintendo 64": require("../assets/game app images/Nintendo 64.png"),
    "Nintendo GameCube": require("../assets/game app images/Nintendo Gamecube.png"),
    "Nintendo DS": require("../assets/game app images/Nintendo DS.png"),
    "Nintendo 3DS": require("../assets/game app images/Nintendo 3DS.png"),
    "Wii": require("../assets/game app images/Wii.png"),
    "Wii U": require("../assets/game app images/Wii U.png"),
    "Nintendo Switch": require("../assets/game app images/Nintendo Switch.png"),
    "Nintendo Switch 2": require("../assets/game app images/Nintendo Switch 2.png"),
    "PlayStation": require("../assets/game app images/PlayStation.png"),
    "PlayStation 2": require("../assets/game app images/PlayStation 2.png"),
    "PlayStation 3": require("../assets/game app images/PlayStation 3.png"),
    "PlayStation 4": require("../assets/game app images/PlayStation 4.png"),
    "PlayStation 5": require("../assets/game app images/PlayStation 5.png"),
    "Sega Master System": require("../assets/game app images/Sega Master System.png"),
    "Sega Genesis": require("../assets/game app images/Sega Genesis.png"),
    "Sega Game Gear": require("../assets/game app images/Sega Game Gear.png"),
    "Sega Saturn": require("../assets/game app images/Sega Saturn.png"),
    "Sega Dreamcast": require("../assets/game app images/Sega Dreamcast.png"),
    "Steam": require("../assets/game app images/Steam.png"),
    "PC": require("../assets/game app images/PC.png"),
    "Xbox": require("../assets/game app images/Xbox.png"),
    "Xbox 360": require("../assets/game app images/Xbox 360.png"),
    "Xbox One": require("../assets/game app images/Xbox One.png"),
    "Xbox Series X/S": require("../assets/game app images/Xbox Series X:S.png")
  };
  